In [1]:
!pip install numpy


In [3]:
import numpy as np

# 定义读取矩阵的函数
def read_matrix_from_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
        matrix = []
        for line in lines:
            row = list(map(float, line.split()))
            matrix.append(row)
        return np.array(matrix)



In [4]:
# 从文件读取矩阵
matrix_file_path = 'nimatrix.txt'
matrix = read_matrix_from_file(matrix_file_path)

In [5]:
# 计算矩阵的逆
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("矩阵的逆:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("矩阵不可逆")

矩阵的逆:
[[-0.  1. -0.  1.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [-0. -1. -1. -1.]]
